#!/usr/bin/env bash
deactivate() {

    unset DEVOPS_BOX 2>/dev/null

    if ! [ -z "${_OLD_DEVOPS_BOX_PATH}" ] ; then
        PATH="$_OLD_DEVOPS_BOX_PATH"
        export PATH
        unset _OLD_DEVOPS_BOX_PATH
    fi

    if ! [ -z "${_OLD_DEVOPS_BOX_PS1+_}" ] ; then
        PS1="$_OLD_DEVOPS_BOX_PS1"
        export PS1
        unset _OLD_DEVOPS_BOX_PS1
    fi

    if [ ! "${1-}" = "nondestructive" ] ; then
        unset ssh_me_gently
        unalias devops box box11 box12 box13 box14 sshd
        unset -f deactivate
    fi
}
# unset irrelevant variables
deactivate nondestructive

DEVOPS_BOX=$(pwd)
chmod 600 ssh/*

ssh_me_gently() {
    ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ${DEVOPS_BOX}/ssh/id_rsa 192.168.10.$1
}
alias devops='ssh_me_gently 100'
alias box='ssh_me_gently 100'
alias box11='ssh_me_gently 11'
alias box12='ssh_me_gently 12'
alias box13='ssh_me_gently 13'
alias box14='ssh_me_gently 14'
alias sshd='ssh_me_gently'

_OLD_DEVOPS_BOX_PATH="$PATH"
PATH="$DEVOPS_BOX/bin:$PATH"
export PATH

if [ -z "${DEVOPS_BOX_DISABLE_PROMPT-}" ] ; then
    _OLD_DEVOPS_BOX_PS1="${PS1-}"
    if [ "x" != x ] ; then
        PS1="${PS1-}"
    else
        PS1="(DevOps-box) ${PS1-}"
    fi
    export PS1
fi

# This should detect bash and zsh, which have a hash command that must
# be called to get it to forget past commands.  Without forgetting
# past commands the $PATH changes we made may not be respected
if [ -n "${BASH-}" ] || [ -n "${ZSH_VERSION-}" ] ; then
    hash -r 2>/dev/null
fi
