# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  1.upto(4) do |i|
    config.vm.define "machine#{i}" do |node|
      node.vm.synced_folder "../", "/project", disabled: true
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "machine#{i}"
      node.vm.network "private_network", ip: "192.168.10.1#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus = 1
        vb.name = "machine#{i}"
      end
      config.vm.provision "file", source: "../ssh/config", destination: "/home/vagrant/.ssh/config"
      config.vm.provision "file", source: "../ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
      config.vm.provision "file", source: "../ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
      config.vm.provision :shell do |s|
        ssh_pub_key = File.readlines("../ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
            mkdir -p /root/.ssh
            mkdir -p /home/vagrant/.ssh
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
            chmod 600 ~/.ssh/authorized_keys
            chmod 600 /home/vagrant/.ssh/authorized_keys
            chmod 600 /root/.ssh/authorized_keys
        SHELL
      end
    end
  end
end
